# -*- coding: utf-8 -*-
"""dados_desenv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnH-j_iciKh5rpykXwtHqq8uLWoFohdu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

produtos = {
    "Dom Casmurro":       ("Literatura", 35.90),
    "O Pequeno Príncipe": ("Infantil",   29.90),
    "Sapiens":             ("Ciências",   54.90),
    "Python para Dados":  ("Tecnologia", 89.90),
    "Clean Code":         ("Tecnologia", 95.00),
    "Harry Potter Vol.1": ("Fantasia",   49.90),
    "Atomic Habits":      ("Autoajuda",  44.90),
    "A Arte da Guerra":   ("Filosofia",  32.00),
    "Cosmos":             ("Ciências",   62.50),
    "Cem Anos de Solidão":("Literatura", 39.90),
}

vendedores = ["Ana Lima", "Carlos Mendes", "Bruno Costa", "Fernanda Rocha"]
regioes    = ["Sudeste", "Sul", "Nordeste", "Norte", "Centro-Oeste"]
datas      = pd.date_range("2024-01-01", "2024-06-30", periods=50)

nomes_prod = np.random.choice(list(produtos.keys()), 50)

dados = {
    "id_venda":   range(1, 51),
    "data":       datas.strftime("%Y-%m-%d"),
    "produto":    nomes_prod,
    "categoria":  [produtos[p][0] for p in nomes_prod],
    "quantidade": np.random.randint(1, 6, 50),
    "preco_unit": [produtos[p][1] for p in nomes_prod],
    "vendedor":   np.random.choice(vendedores, 50),
    "regiao":     np.random.choice(regioes, 50),
}

df = pd.DataFrame(dados)
df["total_venda"] = df["quantidade"] * df["preco_unit"]

# Salva como CSV
df.to_csv("vendas_livraria.csv", index=False)

df.head(10)

"""Desafio 1

criando o faturamento mes
"""

df['data'] = pd.to_datetime(df['data'])
df['mes'] = df['data'].dt.month

faturamento_mes = df.groupby('mes')['total_venda'].sum()

"""grafico"""



plt.figure(figsize=(10, 5))
plt.plot(faturamento_mes.index, faturamento_mes.values)
plt.title('Faturamento mensal ao mes')
plt.xlabel('MÊS')
plt.ylabel('VALOR')
plt.show()

"""DESAFIO 3"""

ticket_medio = df.groupby('vendedor')['total_venda'].mean().sort_values(ascending=False)

print("Ticket Médio por Vendedor:")

print(f"O vencedor é: {ticket_medio.idxmax()} com R$ {ticket_medio.max():.2f}")

"""DESAFIO 4"""

vendas_altas = df[df['total_venda'] > 200]

top_categorias = vendas_altas['categoria'].value_counts()

print("Categorias que dominam vendas acima de R$ 200:")
print(top_categorias)

"""DESAFIO 5"""

df_null = pd.DataFrame(np.nan, index=range(5), columns=df.columns)
df_com_erro = pd.concat([df, df_null])

print("Valores nulos encontrados:")
print(df_com_erro.isnull().sum())

df_limpo = df_com_erro.dropna()

df_limpo